### ISSUE TITLE
Higher QV in plant trio HiFi assembly using paternal kmer than offspring kmer

### ISSUE THREAD

**Issue by baozg** [lh3/yak#11]
Hi, @lh3 

We use the `hifiasm` trio mode to assemble a high het plant genome (320Mb, 1.8% het, pat and mat 50x illumina, F1 have 100x Illumina and HiFi ). In the `yak trioeval` result, the switch error and hamming error is low (pat: 0.38%/0.43%; mat: 1.1%/0.54%). It is a dioecy plant, but unlike human,it is usually hunderads of kb region for sex (sex-determing region in autosome).

By the way, the HiC mode have a good performance on the plant genome (hap1: 0.51% / 3.3% ; hap2: 0.49%/2.61% )

| Type       | Hap  | Switch | Hamming |
|------------|------|--------|---------|
| Trio       | hap1 | 0.49%  | 0.59%   |
| Trio       | hap2 | 0.56%  | 1.13%   |
| Trio-check | hap1 | 0.44%  | 0.39%   |
| Trio-check | hap2 | 0.55%  | 1.12%   |
| HiC        | hap1 | 0.50%  | 2.62%   |
| HiC        | hap2 | 0.52%  | 3.31%   |

Trio version have manual check in the HiC heatmap (https://github.com/baozg/phased-assembly-check) and manually resuce three unitig (https://github.com/chhylp123/hifiasm/issues/115#issuecomment-836707771)

But when we use the `yak qv`, the offspring shows a lower qv than using the matched parent‘s illumina data.

| Assembly   | QV_kmer | QV     |
|------------|---------|--------|
| hap1 (pat) | pat     | 46.475 |
| hap1 (pat) | F1      | 39.931 |
| hap1 (mat) | mat     | 42.899 |
| hap1 (mat) | F1      | 38.986 |

Here is the command I use:

```shell
CentOS 7.5

## hifiasm 

### yak count
yak count -k31 -b37 -t16 -o pat_k31.yak <(cat pat.Clean.R1.fq.gz pat.Clean.R2.fq.gz) <(cat pat.Clean.R1.fq.gz pat.Clean.R2.fq.gz)

### trio mode (0.14.2-r315)

hifiasm -o F1.asm -t32 -1 pat.yak -2 mat.yak F1.ccs.fq.gz

### HiC mode (0.15-r327)
hifiasm -o F1.asm -t32 --h1 F1.Clean.R1.fq.gz --h2 F1.Clean.R2.fq.gz F1.ccs.fq.gz


### trioeval (yak 0.1-r62-dirty)

yak trioeval pat.yak mat.yak F1.asm.trio.hap1.p_ctg.fasta > hap1.hic.trioeval
yak trioeval pat.yak mat.yak F1.asm.trio.hap2.p_ctg.fasta > hap2.hic.trioeval


### qv 

yak qv -t 32 -p -K2g -l 100k F1.yak F1.asm.trio.hap1.fasta > F1.hap1.qv
yak qv -t 32 -p -K2g -l 100k F1.yak F1.asm.trio.hap2.fasta > F1.hap2.qv
yak qv -t 32 -p -K2g -l 100k pat.yak F1.asm.trio.hap1.fasta > pat.hap1.qv
yak qv -t 32 -p -K2g -l 100k mat.yak F1.asm.trio.hap2.fasta > mat.hap2.qv

```

**Comment by lh3** [comment]
Don't use parental k-mers to evaluate parental haplotypes. This would violate the assumption behind yak qv.

**Comment by baozg** [comment]
Thanks for promptly reply. But for a HiFi assembly, qv 36 seems too low. Do you have any suggesstions for increase the QV? In the hifiasm-phase paper, the QV is ~50.
