### ISSUE TITLE
Is yak inspect -p still supported

### ISSUE THREAD

**Issue by Dmitry-Antipov** [lh3/yak#13]
In the readme I see 

 print k-mer histogram
./yak inspect sr.yak > sr.hist
 print k-mers (warning: large output)
./yak inspect -p sr.yak > sr.kmers

But actually both these variants just print k-mer histogram. Is there any way to get k-mers themselves from the yak file?

**Comment by lh3** [comment]
Actually this is an error in README. `inspect` doesn't support `-p`. Sorry.
