### ISSUE TITLE
zcat stream error

### ISSUE THREAD

**Issue by tinyfallen** [lh3/yak#22]
Dear developer,

Thanks for the software.

When submitting the command in a script via SGE cluster, it failed and the log said:

/sge/default/spool/c5/job_scripts/1124529: line 1: syntax error near unexpected token \`('
/sge/default/spool/c5/job_scripts/1124529: line 1: `yak count -o k41.yak -k 41 -b 37 -t 14 <(zcat NGS.reads.r1.fq.gz NGS.reads.r2.fq.gz) <(zcat NGS.reads.r1.fq.gz NGS.reads.r2.fq.gz)'

Could you please give some advies how to deal with the issue?

Best regards.

**Comment by wulj1** [comment]
i do not think it is something wrong with yak...

**Comment by aabaricalla** [comment]
I had the same problem with another program and I found this:

Need enable `process substitution` by setting the posix previous to my command: `set +o posix` . 

Original post: https://github.com/caro46/Tetraploid_project/blob/master/platanus.md

Hope this can be useful.

**Comment by lh3** [comment]
You need to use bash. "sh" doesn't work with `<()`.

**Comment by tinyfallen** [comment]
> set +o posix

So many thanks for your reply! I did not understand your meaning before. This time I just directly add this command and it helps me solve this problem!
