### ISSUE TITLE
Is Hifi and Short Read Combined Counting Possible?

### ISSUE THREAD

**Issue by mir-cat** [lh3/yak#23]
Hi! The question is basically in the title. I was wondering what the command might be if one would like to create a data base from both HiFi and Illumina short reads. Is there a way to merge two yak files after counting? Should they be input all together to the same `yak count` call?

**Comment by lh3** [comment]
Yes
```sh
yak count -o out.yak <(zcat *.fastq.gz) <(zcat *.fastq.gz)
```
