### ISSUE TITLE
dumpped the hash table to file ".yak"

### ISSUE THREAD

**Issue by Karimi-81** [lh3/yak#7]
Hi everybody,
I encountered with this issue several times. Do you have any idea about this:

[M::worker_pipeline::837.296*10.33] processed 94 sequences; 2333500880 distinct k-mers in the hash table
[M::main_count] 2333322325 distinct k-mers after shrinking
[M::yak_ch_dump] dumpped the hash table to file 'ccs.yak'.
[M::main] Version: 0.1-r56
[M::main] CMD: yak count -b37 -t32 -o ccs.yak ccs.fa
[M::main] Real time: 963.551 sec; CPU: 8858.973 sec; Peak RSS: 48.784 GB
yak: main.c:108: main_qv: Assertion `ch' failed.
/var/spool/slurmd/job62811721/slurm_script: line 16: 32703 Aborted                 (core dumped) yak qv -t32 -p -K3.2g -l100k sr.yak "/project/6049291/karimi81/Pacbio_data/wtdbg/mink.srp.fa" > asm-sr.qv.txt
yak: main.c:108: main_qv: Assertion `ch' failed.
/var/spool/slurmd/job62811721/slurm_script: line 17: 32706 Aborted                 (core dumped) yak qv -t32 -p sr.yak "/project/6049291/karimi81/Pacbio_data/lib1/ccs.fastq" > ccs-sr.qv.txt
/var/spool/slurmd/job62811721/slurm_script: line 20: 32707 Segmentation fault      (core dumped) yak inspect ccs.yak sr.yak > ccs-sr.kqv.txt
[M::yak_ch_restore_core] inserted 2132336103 k-mers, of which 2132336103 are new

**Comment by lh3** [comment]
What command lines were you running? Why did you generate ccs.yak but put sr.yak on the qv command line?

**Comment by Karimi-81** [comment]
Thank you. You were right. I missed somethings in my commands. It was solved.
Best wishes

Karim Karimi
Ph.D in  Animal Breeding & Genetics
Postdoctoral Fellowship in Mink Genomics
Department of Animal Science and Aquaculture


Dalhousie University
Tel: (902) 814 4442
________________________________
